name: pytest test_function

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: Install pytest
        run: |
          pipenv install pytest --dev
      - name: pytest split
        run: |
          pipenv run py.test -v ./test/test_split.py
      - name: pytest sort
        run: |
          pipenv run py.test -v ./test/test_sort.py
      - name: pytest merge
        run: |
          pipenv run py.test -v ./test/test_merge.py
